# uses xcodebuild and xcpretty to test Swift snapshots
# on local Mac use the following command to set xcodebuild to use Xcode Beta
# sudo xcode-select -s /Applications/Xcode-Beta.app/Contents/Developer
os: osx

dist: osx

osx_image: xcode8

sudo: required

xcode_project: SwiftyBeaver.xcodeproj

xcode_scheme: SwiftyBeaver (iOS)

xcode_sdk: iphonesimulator8.4

before_install:
- gem install xcpretty
- - export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6 (9.3" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

script:
  - set -o pipefail  # required to let xcpretty use the same exit code like xcodebuild
  - xcodebuild test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" -project SwiftyBeaver.xcodeproj -scheme "SwiftyBeaver (iOS)" -destination name="iPhone 6" | xcpretty -c
